name: "Create cache from tar"
description: "Download tar and unarchive into cache"
inputs:
  url:
    description: "URL of the tar archive"
    required: true
  path:
    description: "Directory to unarchive into"
    required: true
  key:
    description: "Cache key"
    required: true

runs:
  using: "composite"
  steps:
      - name: Setup Cache
        uses: actions/cache@v4
        id: cache-tar
        with:
          path: ${{ inputs.path }}
          key: ${{ inputs.key }}

      - name: Unarchive to cached directory
        if: steps.cache-tar.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p ${{ inputs.path }}
          cd ${{ inputs.path }}
          curl --no-progress-meter ${{ inputs.url }} | tar -Jx --strip-components=1
