name: "Create Vulkan cache"
description: "Cache Vulkan SDK"
outputs:
  cache-hit:
    description: "actions/cache output"
    value: ${{ steps.cache-vulkan.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Get latest Vulkan SDK version
      id: vulkan_sdk_version
      run: |
        echo "VULKAN_SDK_VERSION=$(curl https://vulkan.lunarg.com/sdk/latest/linux.txt)" >> "$GITHUB_ENV"

    - name: Cache Vulkan SDK
      id: cache-vulkan
      uses: ./.github/actions/cache-from-tar
      with:
        url: https://sdk.lunarg.com/sdk/download/latest/linux/vulkan_sdk.tar.xz
        path: ./vulkan_sdk
        key: vulkan-sdk-${{ env.VULKAN_SDK_VERSION }}-${{ runner.os }}
