name: Build Actions Cache

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ubuntu-24-vulkan-cache:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Cache Vulkan SDK
        uses: ./.github/actions/ubuntu-vulkan-cache

  ubuntu-24-spacemit-cache:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Cache SpacemiT Toolchain
        uses: ./.github/actions/ubuntu-spacemit-cache

  windows-2022-rocm-cache:
    runs-on: windows-2022

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Cache ROCm Installation
        uses: ./.github/actions/windows-rocm-cache
