name: Build Actions Cache

on:
  workflow_dispatch: # allows manual triggering
  workflow_call: # reusable
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ubuntu-24-vulkan-cache:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Get latest Vulkan SDK version
        id: vulkan_sdk_version
        run: |
          echo "VULKAN_SDK_VERSION=$(curl https://vulkan.lunarg.com/sdk/latest/linux.txt)" >> "$GITHUB_ENV"

      - name: Cache Vulkan SDK
        uses: ./.github/actions/cache-from-tar
        with:
          url: https://sdk.lunarg.com/sdk/download/latest/linux/vulkan_sdk.tar.xz
          path: ./vulkan_sdk
          key: vulkan-sdk-${{ env.VULKAN_SDK_VERSION }}-${{ runner.os }}

  ubuntu-24-spacemit-cache:
    runs-on: ubuntu-24.04

    env:
      SPACEMIT_IME_TOOLCHAIN_VERSION: "1.1.2"

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Cache SpacemiT Toolchain
        uses: ./.github/actions/cache-from-tar
        with:
          url: https://archive.spacemit.com/toolchain/spacemit-toolchain-linux-glibc-x86_64-v${{ env.SPACEMIT_IME_TOOLCHAIN_VERSION }}.tar.xz
          path: ./spacemit-toolchain
          key: spacemit-ime-toolchain-v${{ env.SPACEMIT_IME_TOOLCHAIN_VERSION }}-${{ runner.os }}

  windows-2022-rocm-cache:
    runs-on: windows-2022

    env:
      # The ROCm version must correspond to the version used in the HIP SDK.
      ROCM_VERSION: "6.4.2"
      HIPSDK_INSTALLER_VERSION: "25.Q3"

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Cache ROCm Installation
        id: cache-rocm
        uses: ./.github/actions/cache-from-exe
        with:
          url: https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-${{ env.HIPSDK_INSTALLER_VERSION }}-WinSvr2022-For-HIP.exe
          path: C:\Program Files\AMD\ROCm
          args: -install
          key: rocm-${{ env.HIPSDK_INSTALLER_VERSION }}-${{ runner.os }}
